apiVersion : apps/v1
kind: Deployment
metadata:
  name: "natephotoapi-064a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "natephotoapi-064a"
  template:
    metadata:
      labels:
        app: "natephotoapi-064a"
    spec:
      containers:
        - name: "natephotoapi-064a"
          image: "nateregistry.azurecr.io/natephotoapi"
          ports:
          - containerPort: 3000